language: node_js
node_js:
  - "0.11"
install:
  - npm install
script:
  - NODE_ENV=test node --harmony-generators
    node_modules/.bin/istanbul cover
    ./node_modules/.bin/_mocha
    --report lcovonly
    -- -u exports
    --recursive
    --bail
after_script: "cat ./coverage/lcov.info | coveralls"